/**
 * Constants for RSS Feeder application
 * Centralized location for all magic numbers and hardcoded strings
 */

// TIMEOUT VALUES (in milliseconds)
const TIMEOUT = {
  RSS_PARSER: 10000,
  HTTP_REQUEST: 10000,
  OBSIDIAN_CONNECTION_TEST: 5000,
  OBSIDIAN_API_REQUEST: 10000,
  GEMINI_API: 30000
};

// RETRY CONFIGURATION
const RETRY = {
  DEFAULT_MAX_RETRIES: 3,
  DEFAULT_RETRY_DELAY: 1000,
  DEFAULT_GEMINI_REQUEST_DELAY: 1000,
  KEYWORD_SUMMARY_RETRIES: 3,
  KEYWORD_SUMMARY_RETRY_DELAY: 2000
};

// HTTP AND NETWORK CONFIGURATION
const HTTP = {
  MAX_REDIRECTS: 3,
  USER_AGENT: 'Personal RSS Feeder Bot/1.0'
};

// ARTICLE LIMITS
const LIMITS = {
  TEST_MODE_ARTICLES: 2,
  SUMMARY_ARTICLES: 10,
  DEFAULT_TEXT_TRUNCATE_LENGTH: 100,
  SUMMARY_PREVIEW_LENGTH: 150,
  DEFAULT_MAX_TAGS_PER_ARTICLE: 3
};

// CRON PATTERNS
const CRON = {
  DEFAULT_SCHEDULE: '0 8,20 * * *',
  TWELVE_HOUR_INTERVAL: '0 */12 * * *'
};

// FILE PATHS AND DIRECTORIES
const PATHS = {
  CONFIG_DIRECTORY: 'config',
  FEEDS_CONFIG_FILE: 'feeds.json',
  TAGS_CONFIG_FILE: 'tags.json',
  DEFAULT_OUTPUT_DIRECTORY: './output',
  DEFAULT_TEMPLATES_DIRECTORY: './templates',
  DEFAULT_PROMPTS_DIRECTORY: './prompts',
  OBSIDIAN_BASE_VAULT_PATH: 'RSS',
  INDEX_FILE_NAME: 'index.md',
  KEYWORD_DIRECTORY_NAME: 'word'
};

// DEFAULT VALUES
const DEFAULTS = {
  TIMEZONE: 'Asia/Tokyo',
  GEMINI_MODEL: 'gemini-2.5-flash',
  OBSIDIAN_API_URL: 'https://127.0.0.1:27124/',
  PARENT_TAG: 'tech',
  TAG_NAME: 'uncategorized',
  ARTICLE_TITLE: 'Untitled',
  ALLOW_MULTIPLE_PARENT_TAGS: false
};

// TIME CALCULATIONS
const TIME = {
  ONE_DAY_MILLISECONDS: 1 * 24 * 60 * 60 * 1000,
  DAEMON_HEARTBEAT_INTERVAL: 1000
};

// ARRAY INDICES AND POSITIONS
const INDICES = {
  TAG_CONFIG_MAX_TAGS_INDEX: 0,
  ARTICLE_INDEX_START: 1,
  ARTICLE_LIST_INDEX_START: 1,
  NEXT_EXECUTIONS_DISPLAY_COUNT: 3,
  FIRST_PARENT_TAG_INDEX: 0,
  TRUNCATE_ELLIPSIS_LENGTH: 3
};

// TEXT AND REGEX PATTERNS
const TEXT = {
  UNKNOWN_DATE_JP: '不明',
  INVALID_FILENAME_CHARS_REGEX: /[<>:"/\\|?*]/g,
  WHITESPACE_REGEX: /\s+/g,
  HTML_TAGS_REGEX: /<[^>]*>/g
};

// FALLBACK VALUES
const FALLBACKS = {
  TAGS: ['uncategorized']
};

module.exports = {
  TIMEOUT,
  RETRY,
  HTTP,
  LIMITS,
  CRON,
  PATHS,
  DEFAULTS,
  TIME,
  INDICES,
  TEXT,
  FALLBACKS
};
